{% set name = "azure-mgmt-media" %}
{% set version = "10.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: d654dce92a85c3aeb251a7e0d0c8d8fa377d26ae4d38836ef69b85c9b4869113

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - setuptools
    - wheel
    - python
    - pip
  run:
    - python
    - msrest >=0.7.1
    - azure-common >=1.1,<2
    - azure-mgmt-core >=1.3.0,<2.0.0

# Tests are required azure-mgmt-storage package which is not part of this package.
# Only pip check is performed.
test:
  imports:
    - azure.mgmt.media
    - azure.mgmt.media.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Media Services Client Library for Python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: Microsoft Azure Media Services Client Library for Python
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
